development:
# Configure available database sessions. (required)
  clients:
    default:
      uri: <%=['MONGODB_URI']%>
      options: 
        consistency: :strong
        max_retries: 30
        retry_interval: 1
        timeout: 15
test:
  clients:
    default:
      database: smarttools_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
production:
  # Configure available database sessions. (required)
  clients:
    default:
      # The standard MongoDB connection URI allows for easy replica set 
      # connection setup. 
      # Use environment variables or a config file to keep your 
      # credentials safe.
      uri: <%=['MONGODB_URI']%>
      options: 
        connect_timeout: 15