development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: heroku_5jh1srk7
      # Provides the hosts the default client can connect to. Must be an array
      # of host:port pairs. (required)
      hosts: <%= ENV['MONGODB_URI']%>
      
   
test:
  clients:
    default:
      database: heroku_5jh1srk7
      hosts: <%= ENV['MONGODB_URI']%>
      

production:
  clients:
    default:
      database: heroku_5jh1srk7
      hosts: <%= ENV['MONGODB_URI']%>
      